<h1>Test</h1>

<?php
/** @var Perspective\Review\Block\Product\Review $block */
?>
<ul>
    <?php
    $comments = $block->getReviews();
    ?>

    <?php foreach ($comments as $comment) : ?>
        <li>
            <?= $comment->getDetail() ?> (<?= $comment->getCreatedAt() ?>)
            <?php if ($comment->getUser()) : ?>
                <?= $block->escapeHtml($comment->getUser()->getFirstname()) ?> <?= $block->escapeHtml($comment->getUser()->getLastname()) ?>
            <?php else : ?>
                Anonymous
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
    <div class="block-content">
        <form action="<?= $block->escapeUrl($block->getUrl('perspective/index/post')) ?>"
              class="review-form"
              method="post"
              id="review-form"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields_before') ?>

            <fieldset class="fieldset review-fieldset">
                <input type="hidden" name="id" value="<?= $block->getProduct()->getId() ?>">
                <div class="field review-field-text required">
                    <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
                    <div class="control">
                        <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
                </div>
            </div>
        </form>
