<h2>Perspective Reviews</h2>

<?php
/** @var Perspective\Review\Block\Product\Review $block */
/** @var Magento\Framework\Escaper $escaper */

$comments = $block->getReviews();
?>
<ul>
    <?php foreach ($comments as $comment) : ?>
        <li>
            <?php if ($comment->getUser()) : ?>
                <h3>
                    <?= $block->escapeHtml($comment->getUser()->getFirstname()) ?>
                    <?= $block->escapeHtml($comment->getUser()->getLastname()) ?>
                </h3>
            <?php else : ?>
                <h3>Anonymous</h3>
            <?php endif; ?>
            <p>
                <?= $comment->getDetail() ?>
            </p>
            <div>
                <small>
                    (<?= $comment->getCreatedAt() ?>)
                </small>
            </div>
        </li>
    <?php endforeach; ?>
</ul>

<div class="block review-add">
    <div class="block-title">
        <strong>
            <?= $escaper->escapeHtml(__('Write Your Own Review')) ?>
        </strong>
    </div>
    <div class="block-content">
        <form action="<?= $escaper->escapeUrl($block->getActionUrl()) ?>"
              class="review-form"
              method="post"
              id="review-form"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields_before') ?>

            <fieldset class="fieldset review-fieldset">
                <input type="hidden" name="id" value="<?= $block->getProduct()->getId() ?>">
                <div class="field review-field-text required">
                    <label for="review_field"
                           class="label"
                    >
                        <span><?= $escaper->escapeHtml(__('Review')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="detail" id="review_field" cols="5" rows="3"
                                  data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary">
                        <span><?= $escaper->escapeHtml(__('Submit Review')) ?></span></button>
                </div>
            </div>
        </form>
