<h2>Perspective Reviews</h2>

<?php
/** @var Perspective\Review\Block\Product\ReviewList $block */
/** @var Magento\Framework\Escaper $escaper */

$reviews = $block->getReviewsCollection();
if (!$block->isEnabled()) {
    return;
}
?>

<?= $block->getChildHtml('add-new-form') ?>

<div style="clear: both"></div>


<ul class="items review-items">
    <?php foreach ($reviews as $review) : ?>
        <li class="item review-item">
            <p>
                <small><?= __('Review by:') ?></small>
                <?php if ($userId = $review->getUserId()) : ?>
                    <?php $user = $block->getUserInfo($userId) ?>
                    <strong>
                        <?= $escaper->escapeHtml($user->getFirstname()) ?>
                        <?= $escaper->escapeHtml($user->getLastname()) ?>
                    </strong>
                <?php else : ?>
                    <strong><?= __('Anonymous') ?> </strong>
                <?php endif; ?>
            </p>

            <p>
                <?= $review->getDetail() ?>
            </p>
            <div>
                <small>
                    (<?= $review->getCreatedAt() ?>)
                </small>
            </div>
        </li>
    <?php endforeach; ?>
</ul>



