<h2>Perspective Reviews</h2>

<?php
/** @var Perspective\Review\Block\Product\ReviewList $block */
/** @var Magento\Framework\Escaper $escaper */

$reviews = $block->getReviewsCollection();
if (!$block->isEnabled()) {
    return;
}
?>
<div class="block review-add">
    <div class="block-title">
        <strong>
            <?= $escaper->escapeHtml(__('Write Your Own Review')) ?>
        </strong>
    </div>
    <div class="block-content">
        <form action="<?= $escaper->escapeUrl($block->getActionUrl()) ?>"
              class="review-form"
              method="post"
              id="review-form"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields_before') ?>

            <fieldset class="fieldset review-fieldset">
                <input type="hidden" name="id" value="<?= $block->getProduct()->getId() ?>">
                <div class="field review-field-text required">
                    <label for="review_field"
                           class="label"
                    >
                        <span><?= $escaper->escapeHtml(__('Review')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="detail" id="review_field" cols="5" rows="3"
                                  data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary">
                        <span><?= $escaper->escapeHtml(__('Submit Review')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div style="clear: both"></div>


<ul class="items review-items">
    <?php foreach ($reviews as $review) : ?>
        <li class="item review-item">
            <p>
                <small><?= __('Review by:') ?></small>
                <?php if ($userId = $review->getUserId()) : ?>
                    <?php $user = $block->getUserInfo($userId) ?>
                    <strong>
                        <?= $escaper->escapeHtml($user->getFirstname()) ?>
                        <?= $escaper->escapeHtml($user->getLastname()) ?>
                    </strong>
                <?php else : ?>
                    <strong><?= __('Anonymous') ?> </strong>
                <?php endif; ?>
            </p>

            <p>
                <?= $review->getDetail() ?>
            </p>
            <div>
                <small>
                    (<?= $review->getCreatedAt() ?>)
                </small>
            </div>
        </li>
    <?php endforeach; ?>
</ul>



